'use server';

import { Resend } from 'resend';

/**
 * sendSubcontractorReportAction - Uses the Resend API to send a filtered 
 * snagging report PDF to a subcontractor.
 */
export async function sendSubcontractorReportAction({
  email,
  name,
  projectName,
  areaName,
  pdfBase64,
  fileName
}: {
  email: string;
  name: string;
  projectName: string;
  areaName: string;
  pdfBase64: string;
  fileName: string;
}) {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey || apiKey === 'your_resend_api_key_here' || apiKey === '') {
    console.error('RESEND_API_KEY is not set in environment variables.');
    return { 
      success: false, 
      message: 'Email service not configured.' 
    };
  }

  const resend = new Resend(apiKey);

  try {
    const { data, error } = await resend.emails.send({
      from: 'snagging@site-command.com',
      to: [email],
      subject: `Snagging Tasks: ${projectName} - ${areaName}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #334155;">
          <h1 style="color: #1e40af; border-bottom: 2px solid #f97316; padding-bottom: 10px;">Snagging Report</h1>
          <p>Hello <strong>${name}</strong>,</p>
          <p>Please find the attached PDF report containing snagging items assigned to your trade at <strong>${projectName} (${areaName})</strong>.</p>
          <p>These items require your immediate attention.</p>
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0; font-size: 14px;"><strong>Project:</strong> ${projectName}</p>
            <p style="margin: 5px 0 0 0; font-size: 14px;"><strong>Area:</strong> ${areaName}</p>
          </div>
          <p style="font-size: 12px; color: #64748b; margin-top: 30px;">
            This is an automated report generated by SiteCommand.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: fileName,
          content: pdfBase64,
        },
      ],
    });

    if (error) {
      console.error('Resend Transmission Error:', error);
      return { success: false, message: error.message };
    }

    return { success: true, message: `Report successfully sent to ${email}.` };
  } catch (err: any) {
    console.error('Server Side Email Error:', err);
    return { success: false, message: err.message || 'Error occurred during transmission.' };
  }
}

/**
 * proxyImageAction - Fetches an external image URL from the server side
 * to bypass browser CORS restrictions during PDF generation.
 */
export async function proxyImageAction(url: string): Promise<string | null> {
  if (!url) return null;
  if (url.startsWith('data:')) return url;

  try {
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'image/*'
      },
      cache: 'no-store'
    });

    if (!response.ok) {
      console.error(`Proxy failed to fetch image: ${response.status} ${response.statusText}`);
      return null;
    }
    
    const arrayBuffer = await response.arrayBuffer();
    const base64 = Buffer.from(arrayBuffer).toString('base64');
    const contentType = response.headers.get('content-type') || 'image/jpeg';
    
    return `data:${contentType};base64,${base64}`;
  } catch (err) {
    console.error("PDF Image Proxy Error:", err);
    return null;
  }
}

export type FormState = {
  message: string;
  success: boolean;
};

export async function createSnaggingItemAction(): Promise<FormState> {
  return { success: false, message: 'Deprecated.' };
}

export async function updateSnaggingItemAction(): Promise<FormState> {
  return { success: false, message: 'Deprecated.' };
}
