
'use server';

import { Resend } from 'resend';

/**
 * sendSubcontractorReportAction - Uses the Resend API to send a filtered 
 * snagging report PDF to a subcontractor.
 */
export async function sendSubcontractorReportAction({
  email,
  name,
  projectName,
  areaName,
  pdfBase64,
  fileName
}: {
  email: string;
  name: string;
  projectName: string;
  areaName: string;
  pdfBase64: string;
  fileName: string;
}) {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey || apiKey === 'your_resend_api_key_here' || apiKey === '') {
    console.error('RESEND_API_KEY is not set in environment variables.');
    return { 
      success: false, 
      message: 'Email service not configured. Please add RESEND_API_KEY to your system settings.' 
    };
  }

  const resend = new Resend(apiKey);

  try {
    const { data, error } = await resend.emails.send({
      from: 'snagging@site-command.com',
      to: [email],
      subject: `Snagging Tasks: ${projectName} - ${areaName}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #334155;">
          <h1 style="color: #1e40af; border-bottom: 2px solid #f97316; padding-bottom: 10px;">Snagging Report</h1>
          <p>Hello <strong>${name}</strong>,</p>
          <p>Please find the attached PDF report containing snagging items assigned to your trade at <strong>${projectName} (${areaName})</strong>.</p>
          <p>These items require your immediate attention to ensure project milestones are met.</p>
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0; font-size: 14px;"><strong>Project:</strong> ${projectName}</p>
            <p style="margin: 5px 0 0 0; font-size: 14px;"><strong>Area:</strong> ${areaName}</p>
          </div>
          <p style="font-size: 12px; color: #64748b; margin-top: 30px;">
            This is an automated report generated by SiteCommand. Please do not reply directly to this email.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: fileName,
          content: pdfBase64,
        },
      ],
    });

    if (error) {
      console.error('Resend Transmission Error:', error);
      return { success: false, message: error.message };
    }

    return { success: true, message: `Report successfully sent to ${email}.` };
  } catch (err: any) {
    console.error('Server Side Email Error:', err);
    return { success: false, message: err.message || 'An unexpected server error occurred during transmission.' };
  }
}

export type FormState = {
  message: string;
  success: boolean;
};

export async function createSnaggingItemAction(): Promise<FormState> {
  return { success: false, message: 'This action is deprecated. Updates are handled client-side.' };
}

export async function updateSnaggingItemAction(): Promise<FormState> {
  return { success: false, message: 'This action is deprecated. Updates are handled client-side.' };
}
